package com.teamup.teamUp.model.enums;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,

    MATCH_INVITE_RECEIVED,
    MATCH_INVITE_ACCEPTED,

    MATCH_UPDATED,
    MATCH_CANCELLED,
    MATCH_STARTING_SOON,

    JOIN_REQUEST_RECEIVED,
    JOIN_REQUEST_ACCEPTED,
    JOIN_WAITLIST,
    PROMOTED_FROM_WAITLIST,
    MOVED_TO_WAITLIST,

    MATCH_LEFT,

    MATCH_RATING
}
