ALTER TABLE teams
ADD COLUMN overall_rating INTEGER NOT NULL DEFAULT 0,
ADD COLUMN attack_rating INTEGER NOT NULL DEFAULT 0,
ADD COLUMN midfield_rating INTEGER NOT NULL DEFAULT 0,
ADD COLUMN defense_rating INTEGER NOT NULL DEFAULT 0;